### ISSUE TITLE
Reserve capacity in 'HashMap: IntoJson'  

### ISSUE THREAD

**Issue by TheIronBorn** [alex-shapiro/ditto#95]
Should `map_value` here not have the capacity of `self`?  https://github.com/alex-shapiro/ditto/blob/c32f8e0c8281fb558be1142313b2affe62cd953f/src/json.rs#L547-L555
i.e. 
```rust
map_value.0.reserve(self.len());

**Comment by alex-shapiro** [comment]
@TheIronBorn Good catch.
